// webpack-platform/wrapper/src/components/Navbar/index.jsx
import { Link } from "react-router-dom";
import Branch from "./Branch";
import "./style.css";

export default function Navbar({ sitemap }) {

    return (
        <nav id="navbar">
            <Link id="logo" to="/" >Guamgam inc.</Link>
            <div id="links">
                {sitemap.map((item) => <Branch key={item.key} item={item} level={0} />)}
            </div>
            <footer>
                <p className="title">
                    <a href="/" target="_blank" rel="noreferrer">Privacy</a>
                    <span className="separator">|</span>
                    <a href="/" target="_blank" rel="noreferrer">Terms</a>
                    <span className="separator">|</span>
                    <a href="/">EULA</a>
                    </p>
            </footer>
        </nav>);


}

// custom-elements-platform/shell/src/app/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: "./navbar.component.html",
  styleUrls: ["./navbar.component.css"]
})
export class NavbarComponent {
  @Input() sitemap: Array<any> = [];

}

<section id="navbar-main" >
  <a id="logo" href="/">Guamgam inc.</a>
  <div id="links"></div>
  <footer>
    <p class="title">
      <a href="/" target="_blank" rel="noreferrer">Privacy</a>
      <span class="separator">|</span>
      <a href="/" target="_blank" rel="noreferrer">Terms</a>
      <span class="separator">|</span>
      <a href="/">EULA</a>
    </p>
  </footer>
</section>
