// webpack-platform/module/src/components/Card/index.jsx
import { useState } from "react";
import CardStyle from "./styled";


export const modes = { viewer: { action: "edit" }, editor: { action: "close" } }

export default function Card({ title, Viewer, Editor, initialMode }) {

    const [mode, setMode] = useState(initialMode || modes.viewer);

    return (
        <CardStyle active={mode === modes.editor}>
            <div className="header">
                <h2>{title}</h2>
            </div>

            <div className="body">
                {
                    mode === modes.viewer ? Viewer : Editor
                }
            </div>

        </CardStyle>
    );

}

// custom-elements-platform/platform/src/app/components/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: "./card.component.html",
  styleUrls: ["./card.component.css"]
})
export class CardComponent {
  @Input() title?: string;
  mode = { name: "viewer", action: "edit" };

  toggleMode() {
    if (this.mode.name === "viewer")
      this.mode = { name: "editor", action: "close" };
    else
      this.mode = { name: "viewer", action: "edit" };
  }
}

<div class="header">
    <h2>{{title}}</h2>
    <button (click)="toggleMode()">{{mode.action}}</button>
</div>

<div class="body">
    <ng-content *ngIf="mode.name==='viewer'" select="[viewer]"></ng-content>
    <ng-content *ngIf="mode.name==='editor'" select="[editor]"></ng-content>
</div>
